### ISSUE TITLE
Replace hardcoded keys for statistics charts

### ISSUE THREAD

**Issue by abhinavpappu** [HackIllinois/admin-site#96]
Hardcoded keys found here: https://github.com/HackIllinois/admin-site/blob/master/src/components/Stats/index.jsx#L9

Not sure why they were hardcoded in the first place, I think it was because we didn't want to calculate stats for certain keys, but maybe a better implementation would be to hardcode the keys we don't want rather than the ones we do. Another option might be to let the user choose which statistics they want to see (similar to the top React-Select on https://admin.hackillinois.org/users) and save it in localStorage.

Most of the functionality for the statistics charts is implemented in the Stats component in `components/Stats`. This component is used in the Statistics page: `scenes/Statistics` as well as in the Users page: `scenes/Users` (allows you to select a subset of users and calculate statistics for them).

The only prop for the Stats component is `registrations`, a list of all registration objects that you want to calculate stats for. Note that this does not directly correspond to the list of registration objects provided by the API at `/registrations/...`, but rather to the return value of this function: https://github.com/HackIllinois/admin-site/blob/master/src/util/registrations.js#L8, which combines the registration data with the decision, rsvp, and checkin data.

**Comment by estelle0500** [comment]
resolved by #115
